### ISSUE TITLE
已 Star，想请问一下：离线指标和线上指标差距多少？是怎么较小差距的呢

### ISSUE THREAD

**Issue by leonall** [wj19971997/NEWS-RECOMMENDATION#1]

**Comment by wj19971997** [comment]
我这边基本差两个百，增减基本一致；验证集的话从训练集的20w用户中随机划分出5w个，具体做法可以看看代码get_valid_users.py这个文件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leonall"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 下午2:59
收件人: "wj19971997/NEWS-RECOMMENDATION"<NEWS-RECOMMENDATION@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [wj19971997/NEWS-RECOMMENDATION] 已 Star，想请问一下：离线指标和线上指标差距多少？是怎么较小差距的呢 (#1)

**Comment by leonall** [comment]
我是使用全量的用户来做验证，线上线下差别挺大的。感谢分享！
